# Generated by Django 2.2.6 on 2019-12-27 05:33

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peanutapp', '0002_oauth'),
    ]

    operations = [
        migrations.CreateModel(
            name='note',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=3)),
                ('title', models.CharField(max_length=200)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('reg_date', models.DateField()),
            ],
        ),
    ]
