# Generated by Django 2.2.6 on 2019-12-27 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peanutapp', '0003_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='type',
            field=models.CharField(max_length=10),
        ),
    ]
