# Generated by Django 2.2.6 on 2020-01-21 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peanutapp', '0004_auto_20191227_0547'),
    ]

    operations = [
        migrations.CreateModel(
            name='education',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=20)),
                ('edu_category', models.CharField(blank=True, max_length=5, null=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('location', models.CharField(blank=True, max_length=10, null=True)),
                ('sdate', models.DateField(blank=True, null=True)),
                ('edate', models.DateField(blank=True, null=True)),
                ('graduated_yn', models.CharField(blank=True, max_length=2, null=True)),
                ('subject', models.CharField(blank=True, max_length=30, null=True)),
                ('high_category', models.CharField(blank=True, max_length=10, null=True)),
                ('grades', models.CharField(blank=True, max_length=3, null=True)),
                ('uni_category', models.CharField(blank=True, max_length=2, null=True)),
            ],
        ),
    ]
